// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Void> Function()>(symbol: 'foo_allocate')
external ffi.Pointer<ffi.Void> foo_allocate();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(
    symbol: 'foo_free_wrapper')
external void foo_free_wrapper(
  ffi.Pointer<ffi.Void> native_resource,
);
